name: Deploy to EC2

on : 
  push: 
    branches: 
      main


jobs:   
  deploy: 
    name: Push to EC2
    runs-on: ubuntu-latest

    steps :
    - name: Checkout the code 
      uses: actions/checkout@v2

    - name: Execute remote SSH commands using key 
      uses: appleboy/ssh-action@v1
      with:
        host: 65.2.126.163
        username: ubuntu 
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22 
        script: |
          cd deploying-next-app || exit

          git pull origin main

          npm i
          npm run build 

          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start